### ISSUE TITLE
Bot token

### ISSUE THREAD

**Issue by ilevn** [korpf/UncertaintyBotProject#1]
You accidentally published your bot token in both of your files.
I suggest to immediately remove both of them and to revoke the token.

**Comment by korpf** [comment]
Thanks for let me notice it. I use github for this project as sync device between the two PCs I'm working on, so I didn't actually took care of it. I'll be more careful, thanks

**Comment by ilevn** [comment]
I really hate to disturb you again but -as you may not know- github stores a history of all files. So, even though you replaced some parts of the token with stars, a person with melicious intentions could still access the old version of the file and compromise your token. I **strongly** adivce that you revoke the bot token via the revoke command in your botfather chat.
